# my SQLの接続
# docker exec -it gss_management-db-1 mysql -u root 
# mysql> show databases;
# +----------------------------+
# | Database                   |
# +----------------------------+
# | gss_management_development |
# | gss_management_test        |
# | information_schema         |
# | mysql                      |
# | performance_schema         |
# | sys                        |
# +----------------------------+
# mysql> use gss_management_development;
# mysql> show tables;

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db

development:
  <<: *default
  database: gss_management_development

test:
  <<: *default
  database: gss_management_test

production:
  <<: *default
  database: gss_management_production
  username: gss_management
  password: <%= ENV['GSS_MANAGEMENT_DATABASE_PASSWORD'] %>
